# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d19fb7ddf712c1662966fffe02ef50c836adba8807d8916262d65b5cbe8c76f44ba898c6368c25d641867a9db7471e86c7fe6e2f16bf86191a01f991dd989e8

test:
  secret_key_base: 0dd08294b5af4471fef41c635eb320255c8870bc9bc9d253b393c08440439a26a6b94e14bd615bac072b5aad8b057faf6823c90ad4ca4a6f405fca8711492ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
